version: "3.0"

services:

  app:
    build: .
    restart: unless-stopped
    ports:
      - "89:80"
    volumes:
      - ./www:/var/www/html
      - ./log:/var/log/apache2

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    # volumes:
    #   - "data:/var/lib/mysql"
