version: "3.0"

services:

  app:
    image: thiagoyou/cpn-php
    restart: unless-stopped
    container_name: cpn-app
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
      - ./docker-compose/apache/hosts:/etc/hosts
      - ./docker-compose/apache/sites-available:/etc/apache2/sites-enabled/
      - ./docker-compose/log:/var/log/apache2
    ports:
      - "${APP_PORT}:80"

  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: cpn-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker-compose/mysql/data:/var/lib/mysql
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d