version: "3.0"

services:

  app:
    build:
      args:
        user: ${APP_USER}
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: cpn-app
    working_dir: /var/www/html
    volumes:
      - ${APP_DIR}:/var/www/html
      - ./docker-compose/apache/sites-available:/etc/apache2/sites-enabled/
      - ./docker-compose/apache/hosts:/etc/hosts
      - ./docker-compose/log:/var/log/apache2
    ports:
      - "${APP_PORT}:80"
      - "4200:4200"
      - "3000:3000"
    expose: 
      - 80
      - 4200
      - 3000
    links:
      - memcached

  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: cpn-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --connect_timeout=180 --interactive_timeout=180 --wait_timeout=180
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker-compose/mysql/data:/var/lib/mysql
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
        - "11211:11211"

networks:
  default:
    external:
      name: ${NETWORK}