version: "3.0"

services:

  app:
    image: thiagoyou/cpn-php
    restart: unless-stopped
    container_name: cpn-app
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
      - ./apache/hosts:/etc/hosts
      - ./apache/sites-available:/etc/apache2/sites-enabled/
      - ./log:/var/log/apache2
    ports:
      - "${APP_PORT}:80"
    links: 
      - db

  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: cpn-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      #   - "data:/var/lib/mysql"
