version: "3.0"

services:

  app:
    build:
      args:
        user: ${APP_USER}
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: dev-app
    networks:
      - app-network
    working_dir: /var/www/html
    volumes:
      - ${APP_DIR}:/var/www/html
      - ./shared:/shared
      - ./data/apache/sites-enabled:/etc/apache2/sites-enabled/
      - ./data/apache/hosts:/etc/hosts
      - ./data/log:/var/log/apache2
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "${APP_PORT}:80"
      - "443:443"
      - "4200:4200"
      - "3000:3000"
    expose: 
      - 80
      - 4200
      - 3000

  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: dev-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./shared:/shared
      - ./data/mysql/content:/var/lib/mysql
      - ./data/mysql/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks: 
  app-network:
    driver: bridge